### ISSUE TITLE
Blog post on the R-hub blog?

### ISSUE THREAD

**Issue by maelle** [lindbrook/packageRank#4]
:wave: @lindbrook !

Would you be interested in authoring a short blog post on the [R-hub blog](https://blog.r-hub.io/)? It could use parts of the README, and also explain how it is used by you (and others) in practice, for what purpose(s). It could direct readers who got curious to the docs of your package if they want to learn more. :-)

**Comment by lindbrook** [comment]
Sure. Just give me a ballpark figure for the word count. Note that I probably won't be able to get to it till early next year, if that's OK?

**Comment by maelle** [comment]
Awesome, I'll open an issue in the R-hub blog repo with a bit more details.

**Comment by lindbrook** [comment]
Draft submitted.
